services:
  - type: web
    name: linkmagico-chatbot
    env: python
    buildCommand: ./build.sh
    startCommand: python src/main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production


